// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ohcxqgcvqexooqigggii.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9oY3hxZ2N2cWV4b29xaWdnZ2lpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MDczNzksImV4cCI6MjA3MTA4MzM3OX0.rW9-WziMAn2Wxl6ew2KwcZ40CRtMR88ow9eHZmScMIE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});